version: '3.9'

services:
  traefik:
    image: traefik:v3
    command:
      - --configFile=/etc/traefik/traefik.yml
    env_file:
      - .env
    ports:
      - '${HOST_PORT}:80'
      - '${HTTPS_PORT}:443'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik/traefik.yml:/etc/traefik/traefik.yml:ro
      - ./letsencrypt:/letsencrypt
    environment:
      DOMAIN: ${DOMAIN}

  db:
    image: postgres:17
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PORT: ${POSTGRES_PORT}
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    entrypoint: ["./docker-entrypoint.sh"]
    env_file:
      - .env
    environment:
      DATABASE_URL: ${DATABASE_URL}
      BACKEND_PORT: ${BACKEND_PORT}
    labels:
      traefik.enable: 'true'
      traefik.http.routers.backend.rule: 'Host(${DOMAIN}) && PathPrefix(`/api`)'
      traefik.http.services.backend.loadbalancer.server.port: '${BACKEND_PORT}'
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      FRONTEND_PORT: ${FRONTEND_PORT}
    labels:
      traefik.enable: 'true'
      traefik.http.routers.frontend.rule: 'Host(${DOMAIN})'
      traefik.http.services.frontend.loadbalancer.server.port: '${FRONTEND_PORT}'
    depends_on:
      - backend

volumes:
  db_data:
  letesencrypt: 