entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"
    http:
      tls:
        certResolver: "le"

providers:
  docker:
    exposedByDefault: false

api:
  dashboard: true
  insecure: true

certificatesResolvers:
  le:
    acme:
      email: "${LETSENCRYPT_EMAIL}"
      storage: "/letsencrypt/acme.json"
      httpChallenge:
        entryPoint: "web" 